image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - choosenim
sources:
  - https://git.sr.ht/~mjaa/xsdtonim
environment:
  site: mjaa.srht.site
tasks:
  - configure: |
      choosenim 1.6.12 -y
      export PATH=$HOME/.nimble/bin:$PATH
      nimble refresh
  - gen_docs: |
      export PATH=$HOME/.nimble/bin:$PATH
      cd xsdtonim
      nim gen_docs.nims
      tar -czf docs.tar.gz -C htmldocs .
  - upload: |
      if [ "$BUILD_SUBMITTER" != "git.sr.ht" ]; then
        echo "Skipping doc uploading for non-git.sr.ht build"
        exit
      fi
      cd xsdtonim
      hut pages publish -d $site -s /xsdtonim docs.tar.gz
